version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-labda-java-basic"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2wsdxm29lpg2"
s3_prefix = "aws-labda-java-basic"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
