name: Building Java samples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'corretto'
        cache: gradle
        
    - name: Grant execution permissions to all the gradle wrappers
      run: find . -name 'gradlew' -exec chmod +x {} +
      
    - name: Running all the gradle builds
      run: find . -name 'gradlew' -execdir ./gradlew build \;

